# Site settings
title: Amlaan Bhoi
email: abhoi3@uic.edu
description: > # this means to ignore newlines until "baseurl:"
  Grad student @UIC MSCS '19. Computer vision, data & text mining, data science. Occasional iOS development (Swift & ARKit). Former intern <a href="https://www.linkedin.com/company/reliance-communications/">@Reliance</a> and @OSSCube.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abhoi.github.io" # the base hostname & protocol for your site
twitter_username: amlaanb
github_username:  abhoi

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "CS Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
